<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net9.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><AllowUnsafeBlocks>true</AllowUnsafeBlocks><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Compile Include="../../src.WinUI/Services/EditorDocument.cs" Link="EditorDocument.cs"/><Compile Include="../../src/Utils/ImageProcessingHelper.cs" Link="ImageProcessingHelper.cs"/><Compile Include="../../src/Utils/HighlighterStroke.cs" Link="HighlighterStroke.cs"/></ItemGroup></Project>

